### ISSUE TITLE
Suggestion: Move native libs into separate directory in jar

### ISSUE THREAD

**Issue by Sirse** [Vatuu/discord-rpc#14]
Suggestion: Move native libs into a separate directory in .jar
For now, jar application with extracted discord-rpc library seems unstructured (we have few dirs with single files).
Maybe just put all libs into one directory called natives?

**Comment by Vatuu** [comment]
The native libraries are included into the jar archive at the build process, using a separate repository just storing the natives. The natives must be extracted at runtime since they need to be loaded by the OS first before JNA is able to load it. They are stored in your TEMP directory for the duration of the runtime before they are being deleted again. (The upcoming 1.5 Version will move the temp artefact to your home directory, instead of the TEMP directory.)
