### ISSUE TITLE
sh: 1: Syntax error: "(" unexpected when DiscordRPC.discordInitialize is called with applicationID being null

### ISSUE THREAD

**Issue by liquidev** [Vatuu/discord-rpc#26]
Hello, I am trying to use this library in my application, but upon calling `DiscordRPC.discordInitialize()` with a `null` `applicationID` the library prints this in the error output stream:
```
sh: 1: Syntax error: "(" unexpected
```

Maybe a more meaningful error could be printed?

**Comment by DeJayDev** [comment]
I um. No idea what this error is. I blame discordapp, but I can research it for you. 

What OS are you on?

**Comment by liquidev** [comment]
Ubuntu 18.04 LTS.

**Comment by DeJayDev** [comment]
Give me a moment, allow me to ask around.

**Comment by Vatuu** [comment]
You probably expected this, but this library is relying on the original discord-rpc C++ library. We interact with it through the JNA interface. Due to this, exact arguments need to be passed. The library expects a String for the appId, and JNA is redirecting this, but since it's unable to accept ``null``, it takes care of error handling, which leads to JNA freaking out.

So yeah, *technically* this is on JNA, and I don't see much use of null-checking a value that should be a static String.

Thanks for reporting though.

**Comment by liquidev** [comment]
@DeJayDevelopment Sure, ask what you need. Other things I thought may be important:
 - IDE: IntelliJ IDEA 2018.3 EAP
 - Java: OpenJDK 8u181
